

INSERT INTO `Item` (`id`, `title`, `type`, `category`, `grouping`, `information`, `instructionsURL`, `bnfSlug`, `emcId`, `clientId`) 
VALUES
(219,'Adrenaline 1:1000','AMPOULE','DRUG','ALLERGY_ANAPHYLAXSIS',,,,3673,5),
(220,'Adrenaline 1mg 1:10,000','PREFILLED_SYRINGE','DRUG','CARDIOVASCULAR',,,,3448,5),
(221,'Amiodarone 300mg Pre-filled Syringe','PREFILLED_SYRINGE','DRUG','CARDIOVASCULAR',,,,3453,5),
(222,'Aspirin 300mg','TABLET','DRUG','CARDIOVASCULAR',,,,8627,5),
(223,'Atropine 1mg/5ml Prefilled Syringe','PREFILLED_SYRINGE','DRUG','CARDIOVASCULAR',,,,5361,5),
(224,'Benzylpenicillin 600mg','AMPOULE','DRUG','ANTIINFECTION',,,,3828,5),
(225,'Chlorphenamine 10 mg','AMPOULE','DRUG','ALLERGY_ANAPHYLAXSIS',,,,10595,5),
(226,'Co-Amoxiclav 1.2Gm','AMPOULE','DRUG','ANTIINFECTION',,,,7853,5),
(227,'Furosemide 20 mg','AMPOULE','DRUG','CARDIOVASCULAR',,,,11522,5),
(228,'Glucose 10% 500ml I.V. Bag','INJECTION','DRUG','GASTROINTESTINAL',,,,,5),
(229,'Glucose Oral Gel 40%','GEL','DRUG','GASTROINTESTINAL',,,,,5),
(230,'Hydrocortisone 100mg','AMPOULE','DRUG','ALLERGY_ANAPHYLAXSIS',,,,7812,5),
(231,'Naloxone 400Mcg','INJECTION','DRUG','NERVOUS',,,,8967,5),
(232,'Ondansetron 4 mg','INJECTION','DRUG','GASTROINTESTINAL',,,,6469,5),
(233,'Paracetamol 1000mg/100ml I.V.','INJECTION','DRUG','ANALGESICS_ANTISPASMODICS',,,,,5),
(234,'Sodium Chloride 500ml','LIQUID','DRUG','RESUSCITATION',,,,,5),
(235,'Tranexamic Acid 500 mcg','AMPOULE','DRUG','CARDIOVASCULAR',,,,3374,5),
(236,'Bag Valve Mask Adult','NONE','DISPOSABLE','RESUSCITATION',,,,,5),
(237,'Chest Seal','NONE''DRESSING',,'RESUSCITATION',,,,,5),
(238,'Decompression Needles' 14G,'NONE','DISPOSABLE','INJECTION_CATHETERIZATION',,,,,5),
(239,'EZ-IO 15mm Needle','NONE','DISPOSABLE','INJECTION_CATHETERIZATION',,'https://www.teleflex.com/usa/en/product-areas/emergency-medicine/intraosseous-access/arrow-ez-io-system/literature/VA_IOS_EZ-IO_Pocket_Guide.pdf',,,5),
(240,'EZ-IO 25mm Needle','NONE','DISPOSABLE','INJECTION_CATHETERIZATION',,'https://www.teleflex.com/usa/en/product-areas/emergency-medicine/intraosseous-access/arrow-ez-io-system/literature/VA_IOS_EZ-IO_Pocket_Guide.pdf',,,5),
(241,'EZ-IO 45mm Needle','NONE','DISPOSABLE','INJECTION_CATHETERIZATION',,'https://www.teleflex.com/usa/en/product-areas/emergency-medicine/intraosseous-access/arrow-ez-io-system/literature/VA_IOS_EZ-IO_Pocket_Guide.pdf',,,5),
(242,'EZ-IO Gun','NONE','HARDWARE','GENERAL',,'https://www.teleflex.com/usa/en/product-areas/emergency-medicine/intraosseous-access/arrow-ez-io-system/literature/VA_IOS_EZ-IO_Pocket_Guide.pdf',,,5),
(243,'EZ-IO Stabilizer kit','NONE''DRESSING',,'INJECTION_CATHETERIZATION',,'https://www.teleflex.com/usa/en/product-areas/emergency-medicine/intraosseous-access/arrow-ez-io-system/literature/VA_IOS_EZ-IO_Pocket_Guide.pdf',,,5),
(244,'I-Gel Size 3','NONE','DISPOSABLE','RESUSCITATION',,,,,5),
(245,'I-Gel Size 4','NONE','DISPOSABLE','RESUSCITATION',,,,,5),
(246,'I-Gel Size 5','NONE','DISPOSABLE','RESUSCITATION',,,,,5),
(247,'Magill Forceps Adult','NONE','HARDWARE','RESUSCITATION',,,,,5),
(248,'Mini-Trach II Portex Minitracheotomy Kit','NONE','DISPOSABLE','RESUSCITATION',,,,,5),
(249,'Nasopharyngeal Airwy Size 6','NONE','DISPOSABLE','RESUSCITATION',,,,,5),
(250,'Nasopharyngeal Airwy Size 7','NONE','HARDWARE','RESUSCITATION',,,,,5),
(251,'Opti Lube','GEL','DISPOSABLE','RESUSCITATION',,,,,5),
(252,'Oropharyngeal Airway Size 2','NONE','DISPOSABLE','RESUSCITATION',,,,,5),
(253,'Oropharyngeal Airway Size 3','NONE','DISPOSABLE','RESUSCITATION',,,,,5),
(254,'Oropharyngeal Airway Size 4','NONE','DISPOSABLE','RESUSCITATION',,,,,5),
(255,'Scalpel SRE Disposable 10 Blade','NONE','DISPOSABLE','RESUSCITATION',,,,,5),
(256,'EndoTracheal Tube Size 6','NONE','DISPOSABLE','RESUSCITATION',,,,,5),
(257,'EndoTracheal Tube Size 7','NONE','DISPOSABLE','RESUSCITATION',,,,,5),
(258,'EndoTracheal Tube Size 8','NONE','DISPOSABLE','RESUSCITATION',,,,,5),
(259,'SAM Pelvic Splint Standard Size','NONE','SPLINT','IMMOBILIZATION',,'https://sammedical.app.box.com/s/0h2vcrp3iz2vrxzaz67750o065eui94s',,,5),
(260,'SAM Splint 36 inch','NONE','SPLINT','IMMOBILIZATION',,,,,5),
(261,'Tourniquet (Trauma)','NONE','DISPOSABLE','RESUSCITATION',,,,,5),
(262,'Giving Set I.V.','NONE','DISPOSABLE','INJECTION_CATHETERIZATION',,,,,5),
(263,'GTN Spray 400Mcg','SPRAY','DRUG','CARDIOVASCULAR',,,,11759,5),
(264,'Ipratropium 500mcg','INHALER','DRUG','RESPIRATORY',,,,3818,5),
(265,'PosiFlush Pre-Filled Saline Syringe (10ml)','PREFILLED_SYRINGE','NONE','INJECTION_CATHETERIZATION',,,,,5),
(266,'Salbutamol 2.5mg/2.5ml','INHALER','DRUG','RESPIRATORY',,,,10256,5),
(267,'Salbutamol Inhaler 100mcg','INHALER','DRUG','RESPIRATORY',,,,12983,5)


